from __future__ import annotations

from collections.abc import Generator
from datetime import UTC, datetime, timedelta

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker
from sqlalchemy.pool import StaticPool

from app.db.base import Base
from app.models.cluster import Cluster
from app.models.enums import (
    ClusterStatus,
    HealthStatus,
    IncidentSeverity,
    IncidentStatus,
    IncidentType,
    PodPhase,
)
from app.models.incident import Incident
from app.models.namespace import KubernetesNamespace
from app.models.pod import Pod
from app.services.analytics_service import AnalyticsService


@pytest.fixture()
def db_session() -> Generator[Session, None, None]:
    engine = create_engine(
        "sqlite+pysqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(bind=engine)

    testing_session_local = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    session = testing_session_local()
    try:
        yield session
    finally:
        session.close()
        Base.metadata.drop_all(bind=engine)


def test_analytics_overview_aggregates_incidents_and_pods(db_session: Session) -> None:
    now = datetime.now(UTC)
    cluster = Cluster(
        name="test-cluster",
        status=ClusterStatus.CONNECTED,
        last_seen_at=now,
    )
    namespace = KubernetesNamespace(cluster=cluster, name="payments", labels={})
    payment_pod = Pod(
        namespace=namespace,
        name="payment-service-9bf",
        phase=PodPhase.RUNNING,
        health_status=HealthStatus.CRITICAL,
        health_score=20,
        restart_count=12,
        ready_containers=0,
        total_containers=1,
        cpu_millicores=80,
        memory_mebibytes=128,
        labels={},
        annotations={},
        last_seen_at=now,
    )
    checkout_pod = Pod(
        namespace=namespace,
        name="checkout-service-77d",
        phase=PodPhase.RUNNING,
        health_status=HealthStatus.WARNING,
        health_score=68,
        restart_count=3,
        ready_containers=1,
        total_containers=1,
        cpu_millicores=420,
        memory_mebibytes=96,
        labels={},
        annotations={},
        last_seen_at=now,
    )
    db_session.add_all(
        [
            cluster,
            namespace,
            payment_pod,
            checkout_pod,
            incident(
                cluster=cluster,
                namespace=namespace,
                pod=payment_pod,
                incident_type=IncidentType.CRASH_LOOP_BACK_OFF,
                severity=IncidentSeverity.CRITICAL,
                status=IncidentStatus.OPEN,
                seen_at=now,
            ),
            incident(
                cluster=cluster,
                namespace=namespace,
                pod=payment_pod,
                incident_type=IncidentType.HIGH_RESTART_COUNT,
                severity=IncidentSeverity.WARNING,
                status=IncidentStatus.ACKNOWLEDGED,
                seen_at=now - timedelta(days=1),
            ),
            incident(
                cluster=cluster,
                namespace=namespace,
                pod=checkout_pod,
                incident_type=IncidentType.TIMEOUT_ERRORS,
                severity=IncidentSeverity.WARNING,
                status=IncidentStatus.RESOLVED,
                seen_at=now - timedelta(days=2),
            ),
        ]
    )
    db_session.commit()

    overview = AnalyticsService(db_session).get_overview(days=7)

    assert overview.total_incidents == 3
    assert overview.open_incidents == 1
    assert overview.critical_incidents == 1
    assert overview.resolved_incidents == 1
    assert sum(point.total for point in overview.incident_trends) == 3
    assert overview.severity_distribution[0].label == "warning"
    assert overview.top_failing_pods[0].pod_name == "payment-service-9bf"
    assert overview.top_failing_pods[0].incident_count == 2
    assert overview.top_cpu_pods[0].pod_name == "checkout-service-77d"
    assert overview.top_restarting_pods[0].restart_count == 12


def incident(
    *,
    cluster: Cluster,
    namespace: KubernetesNamespace,
    pod: Pod,
    incident_type: IncidentType,
    severity: IncidentSeverity,
    status: IncidentStatus,
    seen_at: datetime,
) -> Incident:
    return Incident(
        cluster=cluster,
        namespace=namespace,
        pod=pod,
        incident_type=incident_type,
        severity=severity,
        status=status,
        title=f"{incident_type.value} detected",
        summary="Generated by analytics test.",
        detection_source="rule_engine",
        first_seen_at=seen_at,
        last_seen_at=seen_at,
        resolved_at=seen_at if status == IncidentStatus.RESOLVED else None,
    )
