apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - payment-crashloop.yaml
  - orders-oom.yaml
  - inventory-imagepull.yaml
  - checkout-timeouts.yaml
  - high-cpu.yaml

commonLabels:
  app.kubernetes.io/part-of: kubesight-samples
